# Generated by Django 4.0 on 2021-12-09 02:06

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ml_method', models.CharField(choices=[(app.models.MLMethod['RF'], 'RandomForest'), (app.models.MLMethod['XG'], 'XGBoost')], max_length=20)),
                ('decision', models.CharField(choices=[(app.models.Decision['B'], 'Buy'), (app.models.Decision['S'], 'Sell')], max_length=20)),
                ('date', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=3, max_digits=20)),
                ('profit', models.DecimalField(decimal_places=3, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('adj_close', models.DecimalField(decimal_places=17, max_digits=20)),
                ('close', models.DecimalField(decimal_places=17, max_digits=20)),
                ('volume', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=19)),
                ('created_at', models.DateTimeField()),
                ('user_name', models.CharField(max_length=300)),
                ('text', models.CharField(max_length=400)),
                ('lang', models.CharField(max_length=5)),
                ('tokens', models.CharField(max_length=300)),
                ('subjectivity', models.DecimalField(decimal_places=3, max_digits=3)),
                ('polarity', models.DecimalField(decimal_places=3, max_digits=3)),
                ('analysis', models.DecimalField(decimal_places=0, max_digits=2)),
                ('_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
