# Generated by Django 3.2.9 on 2021-11-29 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_portfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='decision',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='Portfolio_decision',
            field=models.CharField(choices=[('BUY', 'Buy'), ('SEL', 'Sell')], default='BUY', max_length=3),
        ),
    ]
