# Generated by Django 3.2.9 on 2021-11-29 07:17

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211129_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='ML_method',
            field=models.CharField(choices=[(app.models.MLMethod['RF'], 'RandomForest'), (app.models.MLMethod['XG'], 'XGBoost')], max_length=15),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='Portfolio_decision',
            field=models.CharField(choices=[(app.models.Decision['B'], 'Buy'), (app.models.Decision['S'], 'Sell')], max_length=5),
        ),
    ]
