# Generated by Django 3.2.9 on 2021-11-29 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211129_0717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='Portfolio_decision',
            new_name='decision',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='ML_method',
            new_name='ml_method',
        ),
    ]
