# Generated by Django 3.2.9 on 2021-11-29 07:24

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20211129_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='decision',
            field=models.CharField(choices=[(app.models.Decision['B'], 'Buy'), (app.models.Decision['S'], 'Sell')], max_length=20),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='ml_method',
            field=models.CharField(choices=[(app.models.MLMethod['RF'], 'RandomForest'), (app.models.MLMethod['XG'], 'XGBoost')], max_length=20),
        ),
    ]
